# permissions for end users to edit namespaceidentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceidentity-editor-role
rules:
- apiGroups:
  - aqueduct.fb.com
  resources:
  - namespaceidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aqueduct.fb.com
  resources:
  - namespaceidentities/status
  verbs:
  - get
