# permissions for end users to view namespaceidentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceidentity-viewer-role
rules:
- apiGroups:
  - aqueduct.fb.com
  resources:
  - namespaceidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aqueduct.fb.com
  resources:
  - namespaceidentities/status
  verbs:
  - get
